# Site Information
site_name: 北航指北
site_url: https://buaa.info
site_author: Color
site_description: >-
  Here we live together!
  
# Repository
repo_name: buaainfo/buaainfo
repo_url: https://github.com/buaainfo/buaainfo

# Copyright
copyright: 版权所有 &copy; 2022 - 2022 BUAA.info
  
# Configuration
theme:
  name: material

  # Appearance
  palette:
    # Palette toggle for light mode
    - scheme: default 
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: 切换到夜间模式

    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: 切换到日间模式

  icon: 
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  # Web Settings
  font: false # No Google Font
  language: zh
  logo: assets/images/logo.png
  favicon: assets/images/logo.png

  # Features
  features:
    # Navi Settings
    - navigation.instant #instant_load
    - navigation.tabs #pinned_tabs
    - navigation.tracking #right_navi_track
    - navigation.top #go_top
    - navigation.indexes #section_index
    - toc.follow #right_navi_roll
    #- toc.integrate #Navi_integration

    # Search Settings
    - search.highlight
    - search.share
    - search.suggest

    # Header
    - header.autohide

    # Announce
    #- announce.dismiss   Needing

    # Content
    - content.tabs.link
    - content.code.annotate
    - content.tooltips

# Extra files
#extra_css:

# Plugins
plugins:
  - search
  #- tags:
  #    tags_file: tags.md
  #- social: Needing
  #- blog: Needing
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
      enabled: true
  - glightbox

# Customization
extra:
  homepage: https://buaa.info
  #version:
  #  provider: mike Need_to_study
  social:
    - link: https://github.com/buaainfo
      icon: fontawesome/brands/github
      name: BUAAINFO on Github

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

  - abbr
  - attr_list
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  - tables
  - footnotes
  - pymdownx.betterem
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.smartsymbols
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

# Page tree
nav:
  - 首页: 
    - index.md
  - 生存指南:
    - 生存指南: LivingGuide/index.md
  - 常用:
    - 常用站点: CommonUse/site.md
    - 常用电话: CommonUse/phone.md
  - 工具:
    - Tool/index.md
  - 编写规则: 
    - Write/write.md
    - 可用的markdown语言: Write/write-md.md
  - 加入我们: 
    - joinus.md