name: Build documentation with mkdocs and Publish to another repo

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: 3.*
    - name: Install dependencies
      run: |
        pip install \
              mkdocs-material \
              mkdocs-awesome-pages-plugin \
              jieba \
              mkdocs-glightbox \
              mkdocs-git-revision-date-localized-plugin \
              mkdocs-git-authors-plugin \
    - name: Build with mkdocs
      run: mkdocs build
    - name: Commit and publish
      if: ${{ github.ref == 'refs/heads/main' }}
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        PUBLISH_REPOSITORY: ${{ secrets.PUBLISH_REPOSITORY }}
        ACTOR: ${{ secrets.ACTOR }}
      run: |
        remote_repo="https://x-access-token:${ACCESS_TOKEN}@github.com/${PUBLISH_REPOSITORY}.git"
        remote_branch="main"
        git_commit_id=$(git rev-parse --short HEAD)
        mkdir _site_remote && cd _site_remote
        git init
        git config user.name "${ACTOR}"
        git config user.email "${ACTOR}@proton.me"
        git remote add origin $remote_repo
        git remote -v
        git pull origin HEAD:gh-pages
        git rm -rf .
        git clean -fxd
        cp -ar ../site/* ../CNAME ./
        touch .nojekyll
        git add .
        git commit -m "Github Action auto build for https://github.com/buaainfo/buaainfo/commit/${git_commit_id}" --allow-empty
        git push -u origin HEAD:gh-pages
